name: Run Python Telegram Bot

on:
  schedule:
    # Esegui ogni giorno alle 10:00 UTC
    - cron: '0 8 * * *'   # Esegui ogni giorno alle 8:00 UTC -> 10:00 italiane
    - cron: '0 11 * * *'   # Esegui ogni giorno alle 11:00 UTC -> 13:00 italiane
    - cron: '0 15 * * *'   # Esegui ogni giorno alle 15:00 UTC -> 17:00 italiane
    - cron: '0 17 * * *'   # Esegui ogni giorno alle 17:00 UTC -> 19:00 italiane
  workflow_dispatch:  # permette anche di eseguire manualmente

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pytz certifi babel.dates 

      - name: Run bot script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          API_KEY: ${{ secrets.API_KEY }}
        run: python bot1.py
